### ISSUE TITLE
Update tensorflow info? 

### ISSUE THREAD

**Issue by SunBeenMoon** [bitsy-ai/tensorflow-arm-bin#1]
Hi, 

I'm very interested about this post.
https://towardsdatascience.com/real-time-object-tracking-with-tensorflow-raspberry-pi-and-pan-tilt-hat-2aeaef47e134

Learning PID controller in rpi. 

But there is a problem 
![image](https://user-images.githubusercontent.com/78002830/113676553-8658ff00-96f7-11eb-8727-ad7b491f1cb8.png)
It doesn't support anymore. 

Do you know a solution to this content?

Is there any updated content?

**Comment by leigh-johnson** [comment]
Hi @SunBeenMoon, thank you for the kind words! 

Try the following links instead. I'll update the blog post now as well. :bowing_woman: 
https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl

https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_aarch64.whl

**Comment by SunBeenMoon** [comment]
Thank you! I'll try it again.
